services:
  eureka-service-discovery:
    build:
      context: ./eurekaServiceDiscovery
      dockerfile: Dockerfile
    ports:
      - "${EUREKA_SERVER_PORT}:${EUREKA_SERVER_PORT}"
    environment:
      SERVER_PORT: ${EUREKA_SERVER_PORT}

  postgres-db:
    image: postgres
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
      POSTGRES_DB: ${DATASOURCE_DB}
    ports:
      - "5433:5432"
    volumes:
      - .pg-oper-data:/var/lib/postgresql/data
    networks:
      postgres_network:

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - .redis_data:/data
    networks:
      - postgres_network

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: keycloak
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HOSTNAME: localhost
      KC_HTTP_ENABLED: "true"
    ports:
      - "8282:8080" # Порт Keycloak изменен на 8282
    networks:
      - postgres_network
    command: start-dev # Запуск в режиме разработки

networks:
  postgres_network: