apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "exchange-generator-application.fullname" . }}
  labels:
    {{- include "exchange-generator-application.labels" . | nindent 4 }}
data:
  application.yml: |  
    spring:
      application:
        name: exchangeGeneratorApplication
      cloud:
        discovery:
          enabled: false
        config:
          enabled: false
      datasource:
        initialization-mode: never
        enabled: false
      liquibase:
        enabled: false
      security:
        oauth2:
          client:
            registration:
              service-client:
                client-id: exchange-generator-service
                client-secret: dH2ik3GGiu8ubKuyiWu9ZV4Oz9GHg7zy
            provider:
              keycloak:
                token-uri: {{ tpl .Values.keycloak.token_uri . | quote }}
      kafka:
        bootstrap-servers: {{ tpl .Values.kafka.url . | quote }}
        producer:
          bootstrap-servers: {{ tpl .Values.kafka.url . | quote }}
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
          properties:
            acks: all
        admin:
          client-id: yandex-practicum
        properties:
          security.protocol: PLAINTEXT
        template:
          observation-enabled: true
    server:
      port: {{ .Values.service.port }}
    ya-bank:
      gateway: {{ tpl .Values.gateway.service_url . | quote }}
    eureka:
      client:
        enabled: false
    management:
      zipkin:
        tracing:
          endpoint: {{ tpl .Values.zipkin.url . | quote }}
      tracing:
        sampling:
          probability: 1
      endpoints:
        web:
          exposure:
            include: "*"
      metrics:
        export:
          prometheus:
            enabled: true