spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/yaBank
    username: yaBank
    password: 12345

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


