apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "exchange-application.fullname" . }}
  labels:
    {{- include "exchange-application.labels" . | nindent 4 }}
data:
  application.yml: |
    spring:
      application:
        name: exchangeApplication
      cloud:
        discovery:
          enabled: false        
        config:
          enabled: false      
      datasource:
        url: {{ tpl .Values.config.database_url . | quote }}
        username: {{ .Values.config.database_username | quote }}
        driver-class-name: org.postgresql.Driver
      jpa:
        hibernate:
          ddl-auto: none
        show-sql: true
      liquibase:
        enabled: true
      security:
        oauth2:
          resourceserver:
            jwt:
              issuer-uri: {{ tpl .Values.keycloak.issuer_uri . | quote }}
      kafka:
        bootstrap-servers: {{ tpl .Values.kafka.url . | quote }}
        consumer:
          group-id: currency-rate-group
          auto-offset-reset: earliest
          key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
          properties:
            acks: all
        listener:
          observation-enabled: true
          ack-mode: RECORD
        admin:
          client-id: yandex-practicum
        properties:
          security.protocol: PLAINTEXT
        template:
          observation-enabled: true
    server:
      port: {{ .Values.service.port }}
      address: 0.0.0.0
    eureka:
      client:
        enabled: false
    logging:
      level:
        liquibase: DEBUG    
    management:
      zipkin:
        tracing:
          endpoint: {{ tpl .Values.zipkin.url . | quote }}
      tracing:
        sampling:
          probability: 1
      endpoints:
        web:
          exposure:
            include: "*"
      metrics:
        export:
          prometheus:
            enabled: true