spring:
  application:
    name: cashApplication
  cloud:
    config:
      enabled: false
  datasource:
    initialization-mode: never
    enabled: false
  liquibase:
    enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8282/realms/yabank
      client:
        registration:
          service-client:
            client-id: cash-service
            client-secret: dH2ik3GGiu8ubKuyiWu9ZV4Oz9GHg7zy
        provider:
          keycloak:
            token-uri: http://localhost:8282/realms/yabank/protocol/openid-connect/token
  kafka:
    producer:
      bootstrap-servers: pinyaev.kafka.ru:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.JsonSerializer
      properties:
        acks: all
    admin:
      client-id: yandex-practicum
    properties:
      security.protocol: PLAINTEXT
server:
  port: 8092
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
ya-bank:
  gateway: http://localhost:8084/