spring:
  application:
    name: cashApplication
  cloud:
    config:
      enabled: false
  datasource:
    initialization-mode: never
    enabled: false
  liquibase:
    enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URL}
      client:
        registration:
          service-client:
            client-id: cash-service
            client-secret: dH2ik3GGiu8ubKuyiWu9ZV4Oz9GHg7zy
        provider:
          keycloak:
            token-uri: ${KEYCLOAK_TOKEN_URL}
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        acks: all
    admin:
      client-id: yandex-practicum
    properties:
      security.protocol: PLAINTEXT
server:
  port: ${CASH_SERVER_PORT}
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_ZONE}
ya-bank:
  gateway: ${GATEWAY_SERVER_URL}