spring:
  application:
    name: cashApplication
  cloud:
    config:
      enabled: false
  datasource:
    initialization-mode: never
    enabled: false
  liquibase:
    enabled: false

server:
  port: 8092
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
ya-bank:
  gateway: http://localhost:8084/