spring:
  application:
    name: eurekaServiceDiscovery
  cloud:
    config:
      enabled: false

server:
  port: ${EUREKA_SERVER_PORT}
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false

management:
  zipkin:
    tracing:
      endpoint:  {ZIPKIN_SERVER_URL}
  tracing:
    sampling:
      probability: 1