spring:
  application:
    name: exchangeApplication
  datasource:
    url: jdbc:postgresql://localhost:5433/yaBank
    username: yaBank
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8282/realms/yabank
server:
  port: 8087
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
ya-bank:
  gateway: http://localhost:8084/
logging:
  level:
    liquibase: DEBUG
