spring:
  application:
    name: gatewayService
  cloud:
    config:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: accountsApplication
          uri: lb://accountsApplication
          predicates:
            - Path=/accountsApplication/**
          filters:
            - RewritePath=/accountsApplication/?(?<segment>.*), /$\{segment}
        - id: notificationsApplication
          uri: lb://notificationsApplication
          predicates:
            - Path=/notificationsApplication/**
          filters:
            - RewritePath=/notificationsApplication/?(?<segment>.*), /$\{segment}
        - id: blockerApplication
          uri: lb://blockerApplication
          predicates:
            - Path=/blockerApplication/**
          filters:
            - RewritePath=/blockerApplication/?(?<segment>.*), /$\{segment}
        - id: exchangeApplication
          uri: lb://exchangeApplication
          predicates:
            - Path=/exchangeApplication/**
          filters:
            - RewritePath=/exchangeApplication/?(?<segment>.*), /$\{segment}
        - id: cashApplication
          uri: lb://cashApplication
          predicates:
            - Path=/cashApplication/**
          filters:
            - RewritePath=/cashApplication/?(?<segment>.*), /$\{segment}
        - id: transferApplication
          uri: lb://transferApplication
          predicates:
            - Path=/transferApplication/**
          filters:
            - RewritePath=/transferApplication/?(?<segment>.*), /$\{segment}
  datasource:
    initialization-mode: never
    enabled: false
  liquibase:
    enabled: false

server:
  port: ${GATEWAY_SERVER_PORT}
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_ZONE}
