spring:
  application:
    name: notificationsApplication
  datasource:
    url: jdbc:postgresql://localhost:5433/yaBank
    username: yaBank
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8282/realms/yabank
  kafka:
    bootstrap-servers: pinyaev.kafka.ru:9092
    consumer:
      group-id: notify-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: ru.yandex.practicum.yaBank.notificationsApplication.dto
    listener:
      observation-enabled: true
      ack-mode: RECORD
    admin:
      client-id: yandex-practicum
    properties:
      security.protocol: PLAINTEXT
server:
  port: 8081
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    liquibase: DEBUG

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
