spring:
  application:
    name: notificationsApplication
  datasource:
    url: jdbc:postgresql://localhost:5433/yaBank
    username: yaBank
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    enabled: true

server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    liquibase: DEBUG
