spring:
  application:
    name: notificationsApplication
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    enabled: true
  cloud:
    config:
      enabled: false

server:
  port: ${NOTIFICATIONS_SERVER_PORT}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_ZONE}

logging:
  level:
    liquibase: DEBUG