apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cash-application.fullname" . }}
  labels:
    {{- include "cash-application.labels" . | nindent 4 }}
data:
  application.yml: |
    spring:
      application:
        name: cashApplication
      cloud:
        discovery:
          enabled: false        
        config:
          enabled: false      
      datasource:
        initialization-mode: never
        enabled: false
      liquibase:
        enabled: false
      security:
        oauth2:
          client:
            registration:
              service-client:
                client-id: cash-service
                client-secret: dH2ik3GGiu8ubKuyiWu9ZV4Oz9GHg7zy
            provider:
              keycloak:
                token-uri: {{ tpl .Values.keycloak.token_uri . | quote }}
          resourceserver:
            jwt:
              issuer-uri: {{ tpl .Values.keycloak.issuer_uri . | quote }}
    server:
      port: {{ .Values.service.port }}
    ya-bank:
      gateway: {{ tpl .Values.gateway.service_url . | quote }}
    eureka:
      client:
        enabled: false    
    logging:
      level:
        liquibase: DEBUG    
