{
 "title": "Spring Boot Http (3.x)",
 "description": "This dashboard provides real-time monitoring of HTTP requests in a Spring Boot application. It uses Spring Boot Actuator to expose metrics, Prometheus for data collection, and Grafana for visualization.",
 "tags": [ "http" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "label_values(http_server_requests_seconds_sum,application)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(http_server_requests_seconds_sum{application=\"$application\"},cluster)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(http_server_requests_seconds_sum{application=~\"$application\", cluster=~\"$cluster\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Average Request Count (1m)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "2xx Response",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{application=\"$application\",  cluster=~\"$cluster\", instance=~\"$instance\", status=~\"2..\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "4xx Response",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{application=\"$application\",  cluster=~\"$cluster\", instance=~\"$instance\", status=~\"4..\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5xx Response",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{application=\"$application\",  cluster=~\"$cluster\", instance=~\"$instance\", status=~\"5..\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Average Latency (1m)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "2xx Response",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_sum{application=\"$application\",  cluster=~\"$cluster\", instance=~\"$instance\", status=~\"2..\"}[1m]) / irate(http_server_requests_seconds_count{application=\"$application\",  cluster=~\"$cluster\", instance=~\"$instance\", status=~\"2..\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "4xx Response",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_sum{application=\"$application\",  cluster=~\"$cluster\", instance=~\"$instance\", status=~\"4..\"}[1m]) / irate(http_server_requests_seconds_count{application=\"$application\",  cluster=~\"$cluster\", instance=~\"$instance\", status=~\"4..\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5xx Response",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_sum{application=\"$application\",  cluster=~\"$cluster\", instance=~\"$instance\", status=~\"5..\"}[1m]) / irate(http_server_requests_seconds_count{application=\"$application\",  cluster=~\"$cluster\", instance=~\"$instance\", status=~\"5..\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}