{
 "title": "Бизнес Метрики Банка",
 "tags": [
  "бизнес",
  "банковские метрики"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Авторизация пользователей",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(user_login_total{status=\"success\"})",
     "legendFormat": "Успешные логины"
    },
    {
     "expr": "sum(user_login_total{status=\"failure\"})",
     "legendFormat": "Неуспешные логины"
    }
   ]
  },
  {
   "title": "Отправка курсов валют",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "currency_rates_send_ok_total", "legendFormat": "Успешно отправлено" },
    {
     "expr": "rate(currency_rates_get_total[5m])",
     "legendFormat": "Ошибки отправки"
    }
   ]
  },
  {
   "title": "Курсов получено из Kafka",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(currency_rates_get_total)", "legendFormat": "Получено курсов" }
   ]
  },
  {
   "title": "Заблокированные операции",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(blocker_operation_total)", "legendFormat": "Заблокированные операции" }
   ]
  },
  {
   "title": "Задержка API: /api/rates",
   "type": "timeseries",
   "description": "Время ответа /api/rates (в секундах)",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "bank_ui_get_rates_duration_seconds_max",
     "legendFormat": "p95 задержка"
    },
    {
     "expr": "avg(rate(bank_ui_get_rates_duration_sum[5m]) / rate(bank_ui_get_rates_duration_count[5m]))",
     "legendFormat": "Средняя задержка"
    }
   ]
  },
  {
   "title": "Ошибки переводов",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bank_operation_transfer_errors_total)",
     "legendFormat": "Ошибки переводов"
    }
   ]
  }
 ]
}