{{- $fullName := include "notifications-application.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
spec:
  selector:
    app: {{ $fullName }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.service.port }}
      name: http